dev: false
project_name: 'TO-DO App'

mongo_db:
  url: 'mongodb://localhost:27017/'
  db: node_todo

connection:
  port: 3000
  host: localhost

nav:
  - name: 'New Todo'
    path: '/app/todo/new-todo'
